apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycapstone
  labels:
    app: mycapstone
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mycapstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mycapstone
    spec:
      containers:
        - image: dockerjsb/capstonedocker
          imagePullPolicy: Always
          name: mycapstone
          ports:
            - containerPort: 80