apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycapstone
  labels:
    app: mycapstone
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mycapstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: mycapstone
    spec:
      containers:
        - image: dockerjsb/capstonedocker:1
          imagePullPolicy: Always
          name: mycapstone
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
              initialDelaySeconds: 5
              periodSeconds: 5
              successThreshold: 1