apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycapstone
  labels:
    app: mycapstone
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycapstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: mycapstone
    spec:
      containers:
        - image: $DOCKER_TAG_VERSION
          imagePullPolicy: Always
          name: mycapstone
          ports:
            - containerPort: 80
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /
              port: 80