cloudfront:
  yml:
version: 2.1
orbs:
  slack: circleci/slack@4.5.0

jobs:
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [ "05:70:10:f4:bf:12:bb:a5:f4:a4:c3:9a:d6:d9:02:8a" ]
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            cd .circleci/ansible/
            BACKEND_IP=`cat inventory.txt | head -2 | tail -1`
            echo "Cnfiguring the server : ${BACKEND_IP}"
            ansible-playbook -i inventory.txt configure-server.yml

workflows:
  default:
    jobs:
      - configure-infrastructure