  version: 2.1
  orbs:
    aws-eks: circleci/aws-eks@0.2.0
    aws-ecr: circleci/aws-ecr@3.1.0
    kubernetes: circleci/kubernetes@0.3.0
  workflows:
    deployment:
      jobs:
        - aws-eks/create-cluster:
            cluster-name: eks-orb-demo-app-deployment
            aws-region: $AWS_DEFAULT_REGION
